language: julia
os:
  - linux
  - windows
julia:
  - 1.4
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("BioBackgroundModels")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
